version: "3.1"

services:
  wordpress:
    build: ./docker/local
    ports:
      - 3030:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
      POUTINE_LOCAL_DEV: 1
    volumes:
      - "./project/uploads:/var/www/html/wp-content/uploads:rw"
      - "./project/themes:/var/www/html/wp-content/themes:rw"
      - "./project/plugins:/var/www/html/wp-content/plugins:rw"
      - "./project/upgrade:/var/www/html/wp-content/upgrade:rw"

  db:
    image: mysql:5.7
    ports:
      - 4306:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - "./db:/var/lib/mysql"
