version: "3.1"

services:
  wordpress:
    image: wordpress:5.6.0
    restart: always
    ports:
      - 3030:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DEBUG: 1
    volumes:
      - "./project/uploads:/var/www/html/wp-content/uploads:rw"
      - "./project/themes:/var/www/html/wp-content/themes:rw"
      - "./project/plugins:/var/www/html/wp-content/plugins:rw"

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 4306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - "./db:/var/lib/mysql"
