version: "3.1"

services:
  wordpress:
    image: wordpress:5.6.0
    restart: always
    ports:
      - 3030:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_LOCAL_DEV', true);
    volumes:
      - "./project/uploads:/var/www/html/wp-content/uploads:rw"
      - "./project/themes:/var/www/html/wp-content/themes:rw"
      - "./project/plugins:/var/www/html/wp-content/plugins:rw"

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 4306:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - "./db:/var/lib/mysql"
